### ISSUE TITLE
Crash to sleep/power screen

### ISSUE THREAD

**Issue by NachtDrache** [ErmanSayin/Themely#45]
First of all, outstanding theme manager! Now for the issue(s):

Random crashes during navigation.
-During scrolling. Just tapping the d-pad up or down, not holding.
-After deleting a theme by holding down X.
-During and after BGM preview.

N3DSXL (Hyrule Gold), 11.2.0-35U, CIA version, Themely 1.2.1

**Comment by ErmanSayin** [comment]
This is most likely fixed in v1.4.0.

**Comment by NachtDrache** [comment]
It happens far less than what it was, but it still happens on occasion. I have a strong suspicion that it's something to do with Luma/B9S than Themely however.
