### ISSUE TITLE
ARM11 Data abort on scrolling

### ISSUE THREAD

**Issue by valuta1995** [ErmanSayin/Themely#91]
3DS model: **New 3DS XL**
3DS version: **Sys 11.5.0-38E**
3DSX or CIA: **CIA** _installed through latest version of FBI_
entrypoint: **Luma3DS - B9S**
Themely version: **1.3.1**

Moving down (dpad) after deleting (hold x, a) a theme.
Expected result: next theme is selected.
Observed result: Themely crashed.
```
Processor:          ARM11 (core 0)
Exception type:     data abort
Current process:    Themely (00400000374E500)
```

**Comment by valuta1995** [comment]
down
down
down
hold [x]
[a]
hold [x]
[a]
down
[y]
[y]
[x]
[x]
hold [x]
[a]
down
[x]
[x]
down
hold [x]
[a]
down
[x]
[x]
down
[x]
[x]
hold [x]
[a]
down
hold [x]
[a]
down
hold [x]
[a]
A crash occurred. (during accepting delete, usually it happens after accepting delete; thus when moving down.)

**Comment by valuta1995** [comment]
Never mind the above.
The crash _always_ seems to happen after the 7th delete (sometimes 6)

**Comment by valuta1995** [comment]
Just crashed after the 6th delete. Moving around after it caused it to crash. Perhaps a memory leak? Does the size of the deleted themes matter?

**Comment by ErmanSayin** [comment]
Fixed. Will be available in v1.3.2

**Comment by valuta1995** [comment]
Just updated to 1.3.2 still have arm 11 data abort. Shall I make a new issue or re-open this one?

**Comment by ErmanSayin** [comment]
Oh, it's still occurring? I'll have to look into this further

**Comment by valuta1995** [comment]
If you need me to do some extra testing (or if you need more info from my side) just ask.

**Comment by ErmanSayin** [comment]
@valuta1995 Can you try out this build? Thanks
[Themely.zip](https://github.com/ErmanSayin/Themely/files/1194487/Themely.zip)

**Comment by valuta1995** [comment]
Not having any issues with that one.

**Comment by ErmanSayin** [comment]
@valuta1995 Great! I guess the issue is fixed. Thanks a lot for helping me out! 😃
